import 'dart:convert';
import 'dart:io';
import 'package:dio/dio.dart';

import 'package:http/http.dart';
import 'package:premiercoach/HomeUI/TableWidget.dart';
import 'package:premiercoach/app_class.dart';
import 'package:premiercoach/model/fixturesMatches.dart';
import 'package:premiercoach/model/formationModel.dart';
import 'package:premiercoach/model/teamRanking.dart';
import 'package:premiercoach/model/user.dart';
import 'package:premiercoach/model/user_ranking_model.dart';

abstract class HomeRepository {
//  Future<User> infoUser();
  Future<MatchInfoModel> matchesInfo(String date);
  Future<List<Tabloue>> getTabloue();
  Future<Squad> getFormation(String team_name);
  Future<RankingModel> getUserRanking();
}

class HomeApi implements HomeRepository {
  Client client = Client();
  String urlInfo = "https://footballcoach.herokuapp.com/personal/info";
  Dio dio = new Dio();
//  @override
//  Future<User> infoUser() async {
//    try {
//      final response =
//          await client.get(urlInfo, headers: {
//            'token':AppClass.token
//          });
//      print(json.decode(response.body));
//      if (response.statusCode == 200) {
//        client.close();
//        return User.fromJson(json.decode(response.body));
//      }
//    } catch (e) {
//      client.close();
//      print(e.toString());
//      throw Exception('Failed to load info of user');
//    }
//  }
  @override
  Future<List<Tabloue>> getTabloue() async{
    try {
      final response = await client.get(AppClass.tableUrl);
      return Autogenerated.fromJson(jsonDecode(response.body)).data.table;
    }
    catch(e){
      throw e;
    }
    finally {
      client.close();
    }
  }
  Future<MatchInfoModel> matchesInfo(String date)async{
    print("URLS ${AppClass.fixturesUrl}");
    String matchesUrl = "http://livescore-api.com/api-client/scores/history.json?&key=${AppClass.key}&secret=${AppClass.secretKey}&competition_id=2&from=${date}";

    try{
      var response = await dio.get("${matchesUrl}");
      print("response ${response.statusCode}");
      print("response ${response.data['success']}");

    if(response.statusCode == 200){
         return MatchInfoModel.fromJson(response.data);
      }else{
        print("response ${response.statusCode}");
      }
    }catch(e){
      print("Error ${e}");
    }
  }
  @override
  Future<Squad> getFormation(String team_name) async{
    String url='https://aifootballcoach.herokuapp.com/recommend?team=${team_name}';
    try {
      final response = await client.get(url);
      print(response.body);
      return Squad.fromJson(jsonDecode(response.body));
    }
    catch(e){
      throw e;
    }
    finally {
      client.close();
    }
  }

  @override
  Future<RankingModel> getUserRanking()async{
    // TODO: implement getUserRanking
    String url='https://footballcoach.herokuapp.com/ranking/scores';
    try {
      final response = await client.get(url,headers: {
         "token" : "${AppClass.token}"
      });
      print((response.body).length);
      print(response.statusCode);
      if(response.statusCode == 200)
        return RankingModel.fromJson(jsonDecode(response.body));
    }
    catch(e){
      throw e;
    }
    finally {
      client.close();
    }
  }
}
