class Autogenerated {
  bool success;
  Data data;

  Autogenerated({this.success, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }
}

class Data {
  List<Tabloue> table;

  Data({this.table});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['table'] != null) {
      table = new List<Tabloue>();
      json['table'].forEach((v) {
        table.add(new Tabloue.fromJson(v));
      });
    }
  }
}

class Tabloue {
  String leagueId;
  String seasonId;
  String name;
  String rank;
  String points;
  String matches;
  String goalDiff;
  String goalsScored;
  String goalsConceded;
  String lost;
  String drawn;
  String won;
  String teamId;
  String competitionId;

  Tabloue(
      {this.leagueId,
        this.seasonId,
        this.name,
        this.rank,
        this.points,
        this.matches,
        this.goalDiff,
        this.goalsScored,
        this.goalsConceded,
        this.lost,
        this.drawn,
        this.won,
        this.teamId,
        this.competitionId});

  Tabloue.fromJson(Map<String, dynamic> json) {
    leagueId = json['league_id'];
    seasonId = json['season_id'];
    name = json['name'];
    rank = json['rank'];
    points = json['points'];
    matches = json['matches'];
    goalDiff = json['goal_diff'];
    goalsScored = json['goals_scored'];
    goalsConceded = json['goals_conceded'];
    lost = json['lost'];
    drawn = json['drawn'];
    won = json['won'];
    teamId = json['team_id'];
    competitionId = json['competition_id'];
  }
}